spring:
  application:
    name: retail-management
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: myuser
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  logging:
    level:
      root: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      org.springframework.transaction: DEBUG
